Resources:
  ApiGatewayCustomDomain:
    Type: AWS::ApiGateway::DomainName
    DependsOn: ApiGatewayRestApi
    Properties:
      RegionalCertificateArn: ${self:provider.config.certificateArn}
      DomainName: ${self:provider.config.domain}
      EndpointConfiguration:
        Types:
          - REGIONAL
