Resources:
  ApiGatewayCustomDomain:
    Type: AWS::ApiGateway::DomainName
    DependsOn: ApiGatewayRestApi
    Properties:
      CertificateArn: ${self:provider.config.certificateArn}
      DomainName: ${self:provider.config.domain}
      EndpointConfiguration:
        Types:
          - EDGE
